### ISSUE TITLE
Long time not responding and got killed automatically

### ISSUE THREAD

**Issue by XingpingGY** [Wanchai290/tmita-optical-cardyomyocyte-analysis#31]
Thanks a lot for the program now I successfully connected the raspberry pi and laptop. When I ran the program on pi it seemed that it was working. But once I opened the software on laptop and input the static address and clicked ok. The software will lose response and just got corruption...
In command shell there was no any errors like this...
`INFO: FrameTCPClientLogger: Initializing connection`
`./run.sh: line 1: 6484 killed`

In the shell on pi it looked like this, no errors as well:
`INFO: FrameTCPSServerLogger:Server initialized and bound to ('192.168.0.10', 47828)`
`Killed`

After long time not responding, the software just collapsed automatically.

**Comment by XingpingGY** [comment]
Good news update. Stable connection was successfully built and frames were transferred. But the camera frames obtained were not consecutive but intermittent. I guess the communication speed is too slow due to protocol or ethernet cable, etc. I will figure out the details limiting the transfer speed next.

**Comment by Wanchai290** [comment]
If I recall correctly, the latest parameters for the image acquisition on the RaspberryPi were MASSIVE. The pictures sent are extremely heavy and their size might be the culprit. You could try reducing the resolution of the RaspberryPi camera and see if it improves. Both processes getting killed on the computer and the RaspberryPi probably means that they took too much memory

**Comment by XingpingGY** [comment]
Yes it is working better when resolution is set lower, but not good enough, I will try to find some other ways to increase the communication speed. Thanks!
