### ISSUE TITLE
[TIxier-Mita lab] Adapt the RaspberryPi script to new communication protocol setup

### ISSUE THREAD

**Issue by Wanchai290** [Wanchai290/tmita-optical-cardyomyocyte-analysis#41]
Integrates the changes of #35 and the necessary changes for the RaspberryPi script to work again

**Comment by XingpingGY** [comment]
Thank you very much for your adaption Wanchai. There is some problems with the Raspberri Pi and the test of your code may be later after it is repaired.

**Comment by XingpingGY** [comment]
Thomas thank you for your work. I have built the connection between raspberrypi and laptop successfully. But once I clicked import from zmq and the software will lost reaction and killed after long time no response... 
![Screenshot from 2023-11-17 17-29-51](https://github.com/Wanchai290/tmita-optical-cardyomyocyte-analysis/assets/92571768/3372da60-d24c-4507-a7fc-c8cc1aa7f401)

**Comment by Wanchai290** [comment]
Huh this is weird. There is a dummy publisher script available to test out the ZMQ socket, could you try it ? https://github.com/Wanchai290/tmita-optical-cardyomyocyte-analysis/blob/41-tmita-adapt-raspi-new-comm-protocol/src/comm_protocol/dummy_zmq_pub_sub/DummyZMQPub.py

It is located in the src/comm_protocol/dummy_zmq_pub_sub directory. Remember to first launch the publisher, then after that start the subscriber (the software itself)

**Comment by Wanchai290** [comment]
Hi, sorry for the late feedback. I have tested the Dummy ZMQ publisher script on two separate machines that were connected together over WiFi, and everything went well. I assume the error you had can come from one of these two things :
- The publisher was launched after the subscriber (if that happens, you can just close the software and launch it again, or switch video feeds)
- There is a bug in the RaspberryPi script that does not allow it to send the frames properly (maybe it crashes ?)

Could you get back to me with additional information about your connection setup ? 
Please notify me if you managed to fix this bug, I will close the PRs and issue associated with it if that's the case.

**Comment by XingpingGY** [comment]
Sorry for the late response...I've been busy with cells last week. I believed I launched subscriber (software in laptop) after publisher(raspberry pi). And the software will be crashed and no response at all. I will test it this afternoon again and I will give you further info after that.

**Comment by XingpingGY** [comment]
I followed the instruction step by step. But once I clicked import from zmq it will lose response...I launched subscriber after publisher surely. Now I would think that it could be that the raspberry pi did not support such software running...Sorry for my late feedback, Thomas.

**Comment by XingpingGY** [comment]
That is alright Thomas. My bad as well...I did not check the file seriously and it turns out to be such a small thing ,lol. Thank you for your effort! Now it is working and the time delay can be reduced to only 1~3 second or so by using zmq library. It could be acceptable though it still has space to be improved. Thank you for your good work!

**Comment by Wanchai290** [comment]
Great news then ! I will push an additional commit that will change the default publishing port in the RaspberryPi script and merge everything into main. About the performance, it will be difficult for me to properly inspects what causes the speed issues, so I'm still thinking whether I can still work on the project from now on (studies are getting a little harsher now)

**Comment by XingpingGY** [comment]
Take your time Thomas, thank you for your efforts so far. It is more important for your own study now:)

**Comment by Wanchai290** [comment]
resolved by #43
